### ISSUE TITLE
Missing Athena JDBC Drivers Cause Failed Spark Cluster Create

### ISSUE THREAD

**Issue by texmachina** [awslabs/harmonize-search-analyze#1]
Hey guys, the linked S3 JDBC driver (AthenaJDBS41-1.0.0) is no longer available at the path in the SparkCluster CloudFormation template (specifically the one referenced in step #4 of the EMR Cluster Bootstrap). This causes the _out of the box_ CloudFormation Template to fail on the EMR cluster creation step.

It looks like the following are available:
```
2017-03-24 17:21:27   10901192 AthenaJDBC41-1.0.1.jar
2017-05-16 18:34:47   11074334 AthenaJDBC41-1.1.0.jar
```

**Comment by rstrahan** [comment]
Hi Jacob, thanks for finding and reporting this! 
I just committed the fix - the template now installs AthenaJDBC41-1.1.0.jar. 
Bob
