### ISSUE TITLE
CF template fails on bootstrap

### ISSUE THREAD

**Issue by sknadella87** [awslabs/harmonize-search-analyze#2]
When we try to directly launch the stack from github, stack fails to create during the bootstrap process

jupyterspark.yaml bootstrap actions are outdated.

**Comment by rstrahan** [comment]
Hi @sknadella87 - Apologies for the issues you've been having. As you likely noticed, this project hasn't been actively maintained for a while, and the issues you've seen are related to incompatibilities introduced in newer versions of some of the dependencies, namely nodejs/npm.
I just pushed some fixes to the repo, and also to the S3 bucket where we publish the CF Templates (aws-bigdata-blogs). You should be able to successfully launch the stack now, using the LaunchStack button in the blog post (or in the repo README).
The version issues affected the bootstrap actions for the EMR cluster, and also affected the build of the search UI component. I validated that both now complete successfully (in my account).
Caveats:  Other aspects of this solution should be updated.. E.g. versions of EMR and ElasticSearch service should be refreshed, the harmonization notebooks need to be updated to handle changes to the data set files that are downloaded, and I also just noticed that the search UI has a year selector that is capped at 2017.  If you are inclined to make updates/improvements, we'll be delighted to receive pull requests :)
Hope this helps get you unstuck. Good luck!
Cheers
Bob
PS You'd asked about the missing vpc.yaml in an earlier post - this is part of the ecs reference architecture project, which we pull in dynamically as a git submodule during the build.
